### PR TITLE
Removed unreliable string check

### PR DESCRIPTION
**Pull request by KoryNunn**
in chrome (43.0.2357.125) :

```
String(WeakMap.prototype)
"[object Object]"
```

### CODE REVIEW

**Comment by medikoo** [comment]
It's intentional. It's a bug in Chrome, which makes implementation incomplete. This function is supposed to return true only if native implementation is reliable

**Comment by KoryNunn** [comment]
So, because chrome's implementation of WeakMap.prototype.toString() isn't exactly '[object WeakMap]', throw the actually functionally to-spec native version out and use the significantly slower ponyfill?

**Comment by medikoo** [comment]
See V8 issue: https://code.google.com/p/v8/issues/detail?id=3619 it should be fixed soon.

Still, polyfill shouldn't be really slower, why you assume it is?

**Comment by KoryNunn** [comment]
Does that break spec? http://www.ecma-international.org/ecma-262/6.0/#sec-weakmap-objects

The polyfilled version is significantly slower than the native version in my use cases. That isn't to say this implementation is slow, I wouldn't expect a polyfilled version to be able to compete with native.

I know I would personally rather the native version than worry about a toString method.

**Comment by medikoo** [comment]
> Does that break spec?

Yes it breaks

> The polyfilled version is significantly slower than the native version in my use cases. That isn't to say this implementation is slow, I wouldn't expect a polyfilled version to be able to compete with native.

Usually first native implementations are slower than polyfills, and sometimes it never changes.
Can you post some test that shows that this polyfil is sifignificantly slower than native? I'll be grateful

**Comment by KoryNunn** [comment]
https://gist.github.com/KoryNunn/c6ca8ef9b40e27b0c042

**Comment by medikoo** [comment]
Thanks, it's test for `get` method, and indeed there's some difference. However I doubt that in real world application it will bring any difference to you (what would be the use case for checking  millions of objects on weakmap, and why 200ms should be considered slow for such operation? :)

It's general problem with microbrenchmarks, that they do not address real problems, results of above benchmark shouldn't be really bothering in my opinion

**Comment by KoryNunn** [comment]
My specific use case, which does get up to the hundreds of thousands of calls area, is in enti: https://github.com/KoryNunn/enti/blob/master/index.js

It is for observable style events, and thus, the few hundred ms does become noticeable if you are working with large datasets.

Also, this effect is compounded significantly on a phone or netbook.

**Comment by medikoo** [comment]
In such case I suggest that you on your own check for existence of `WeakMap`, and manually choose between polyfill and native.

As I checked there's really no room to improve performance of `get` method in polyfill, and relaxing the implementation validation rule may be breaking for others.

**Pull request closed without merging**
