### PR TITLE
Remove `clear` method - closes #2

### LINKED ISSUE #2: Remove `map.clear`
As per TC39 consensus -> https://github.com/rwaldron/tc39-notes/blob/master/es6/2014-11/nov-19.md#conclusionresolution-1

### PR DESCRIPTION
**Pull request by phated**
I've been using this shim and my tests are failing on iojs due to it not having the `clear` method on WeakMaps.  This removes the clear method and its usage as a check for WeakMap implementation.

### CODE REVIEW

**Comment by medikoo** [comment]
Great thanks, it's published as v0.1.3

**Comment by medikoo** [comment]
Sorry for confusion, it's actually published as v1.0.0. I prematurely published it as v0.1.3, it's a breaking change and required a major (v0.1.3 is now shadowed with v0.1.4 that brings v0.1.2 back)

**Comment by phated** [comment]
Good catch.  Just an FYI, semver allows breaking API changes in minor patch versions if you are below 1.0, so you could have published as 0.2.  That being said, I am very happy when dependencies hit 1.0 :100:

**Comment by medikoo** [comment]
@phated Yes I'm aware it could have been 0.2. I just wanted to switch to 1 ;-)

**Pull request merged**
